{{- $secret := (lookup "v1" "Secret" .Release.Namespace "elasticsearch-master-credentials") }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-credentials
  labels:
    app: elasticsearch-master
type: Opaque
data:
  username: {{ "elastic" | b64enc }}
  {{- if $secret }}
  password: {{ index $secret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
