apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-deployer
  namespace: elasticsearch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elasticsearch-deployer
  namespace: elasticsearch
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io", "policy"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch-deployer
  namespace: elasticsearch
subjects:
  - kind: ServiceAccount
    name: elasticsearch-deployer
    namespace: elasticsearch
roleRef:
  kind: Role
  name: elasticsearch-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearch-deployer
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["*"]
  - apiGroups: ["cert-manager.io"]
    resources: ["clusterissuers"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch-deployer
subjects:
  - kind: ServiceAccount
    name: elasticsearch-deployer
    namespace: elasticsearch
roleRef:
  kind: ClusterRole
  name: elasticsearch-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-deployer-token
  namespace: elasticsearch
  annotations:
    kubernetes.io/service-account.name: elasticsearch-deployer
type: kubernetes.io/service-account-token
