---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elasticsearch-credentials
  namespace: elasticsearch
spec:
  encryptedData:
    password: AgCrH7aLUSRanQgukOMOp3LNzI6rt7yHgHWsHwu8ODclVzfbiPD9iM9B0CqzbozINm7PDUnoa3kRlTiCNJSngQaRzM53wRA71PqYgk5e+j5VHqLZ+50FxPrUyB10MkWBc4h7JdIwbYxFqxzC5dXTPJ7+L3F9mAOfA+HfFxOk9i9e7pCLMXQD437gvBtjXbETu/cTZKh2zlTFPbTBG1Mx3X94I+Saxu6kPOcM4x4n13bg4zlmvjvNlkpe9OxaoWPbnFhozrB9pVjkw9kAw8gQs1bpajIPoA3QJDLLuS+YBsW4q/x+dNPbJCK1E9jZ493rJXZ4P2Z3h4T+yD597hXk//VRbb1zZXyODu3o/w5K/56oov64T5kayGuy7WGy5g/V/GQHNmKowifLqrJDMH2u8ZJ4JsYHP6OHNvfTI1AluvLIafx0y6HyxOIYIKer0HkHntupwpKtxayEZNeZDL5KHFytRPwVzgtT2KNg8XpmGI3YNP9MGo4dKVIwhGZU6S8wXnHI7WT6k/1Pbalby03TIrn0POlFoj6/WyuZeNcNm4YittN1GubHEc68e2oqaqF2pn/9h3b26+tI/764k7hlteuKJlwt6TnTgTjV1V0c/ftAL9OkAyqjtv+ZcB+w0DjOKJY1HYotgAnLBacQhvQyUMF6ylF6bkiRpRMR3iMmWYui4yVJef54Mu0tlwndoOncl828WsgZC0dj2PL+psLX+dWjiVeXTsKOCtLC556wHp6lGWHWYpaV9nJu+ToPyg==
    username: AgAvQBF4wbgJKnOBZH6CyLiwfuNqet0EHeXR20kkO/bPW0VaJpWetEuRYelFNUmoZcRsbth27a9gIpYEnrRsvYmCga4dhhgop3a3UN8FAfMG6bGuH4Gesuzq4JSRZZcA3SaNQufUhrj38dJeZzGIBqvKWa4Rtb6uwG/jgOjs5BJMI5Ygx3Lnfz1k+EIhPdAUe6dHZR6thTOmNQiOKPdvXhzXjBHEBA5RQ90jFOXnGb5nkGf4TB5UaH5tOI6lOm1y2zXf+z9qmmRcwr93glnDSG86sE4jg8NgP/fCm1XBlYLP6btmU+m9VGwjrcgLPfSp6v2bZmtXQYs/56iF/WJnktV3dMIcPTIc3CC+py0B5h5TuIqSXou0Vf5cmX6ONdJiVVEZ5ljw0rGVRL0sbx9brqqpuSF7AbM+1D4zDEe1fXad6usC5lcbXvk/ve2wl9ygF76zfouH3OyRbPypUQhFVu8LhnD/QrtdBme1Efnb/LCgxQLADt3pUhfIi6g8yyqVD7lEyAN/UzLf37DoX17+pOKHJpWZ4X0M8O/nyYMKsMcV8hk5B1SEerWY7LkeaoQpcVMRvcV4vyBG9+A1fP6xtnsXEdJjqRDoKo6Z8LVDr98eh6Q9IVesnw4Mwrdct96IEmmJcULtq406ApMxJncEiIN3o2wJZ3UiR4OGRrUHA+Li+TzkSFv4CunMEEJ5yLKYWldMFGqQ9Y0Y
  template:
    metadata:
      name: elasticsearch-credentials
      namespace: elasticsearch
    type: Opaque
